# Generated by Django 4.0.6 on 2022-07-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='dataInserimento',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
