# Generated by Django 4.0.6 on 2022-07-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalleapp', '0002_text_datainserimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='dataInserimento',
        ),
    ]
