# Generated by Django 4.0.6 on 2022-10-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalleapp', '0004_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Configuration',
        ),
    ]
