# Generated by Django 4.0.6 on 2022-10-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalleapp', '0005_rename_settings_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='openaiSessK',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='summaryModel',
            field=models.TextField(max_length=250),
        ),
    ]
