# Generated by Django 4.0.6 on 2022-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalleapp', '0003_remove_text_datainserimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summaryModel', models.CharField(max_length=250)),
                ('openaiSessK', models.CharField(max_length=250)),
                ('nImages', models.IntegerField()),
            ],
        ),
    ]
