# Generated by Django 4.0.6 on 2022-10-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalleapp', '0006_alter_configuration_openaisessk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='openaiSessK',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='summaryModel',
            field=models.CharField(max_length=250),
        ),
    ]
